package com.edureka.module4.exception;

public class MyPackageTwo {
	
	public static void test(){
		System.out.println("Inside the same package");
	}

}
